package com.cd.minecraft.mclauncher.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MOD_ITEMS.
 */
public class ModItems {

    private Long id;
    /** Not-null value. */
    private String modName;
    private String modDesc;
    private String modauthor;
    private String modFile;
    private String modIcon;

    public ModItems() {
    }

    public ModItems(Long id) {
        this.id = id;
    }

    public ModItems(Long id, String modName, String modDesc, String modauthor, String modFile, String modIcon) {
        this.id = id;
        this.modName = modName;
        this.modDesc = modDesc;
        this.modauthor = modauthor;
        this.modFile = modFile;
        this.modIcon = modIcon;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getModName() {
        return modName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setModName(String modName) {
        this.modName = modName;
    }

    public String getModDesc() {
        return modDesc;
    }

    public void setModDesc(String modDesc) {
        this.modDesc = modDesc;
    }

    public String getModauthor() {
        return modauthor;
    }

    public void setModauthor(String modauthor) {
        this.modauthor = modauthor;
    }

    public String getModFile() {
        return modFile;
    }

    public void setModFile(String modFile) {
        this.modFile = modFile;
    }

    public String getModIcon() {
        return modIcon;
    }

    public void setModIcon(String modIcon) {
        this.modIcon = modIcon;
    }

}
