package com.cd.minecraft.mclauncher.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SCRIPT_ITEMS.
 */
public class ScriptItems {

    private Long id;
    /** Not-null value. */
    private String pluginName;
    private String pluginDesc;
    private String pluginauthor;
    private String pluginJsFile;
    private String pluginIcon;
    private String pluginRes;

    public ScriptItems() {
    }

    public ScriptItems(Long id) {
        this.id = id;
    }

    public ScriptItems(Long id, String pluginName, String pluginDesc, String pluginauthor, String pluginJsFile, String pluginIcon, String pluginRes) {
        this.id = id;
        this.pluginName = pluginName;
        this.pluginDesc = pluginDesc;
        this.pluginauthor = pluginauthor;
        this.pluginJsFile = pluginJsFile;
        this.pluginIcon = pluginIcon;
        this.pluginRes = pluginRes;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPluginName() {
        return pluginName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPluginName(String pluginName) {
        this.pluginName = pluginName;
    }

    public String getPluginDesc() {
        return pluginDesc;
    }

    public void setPluginDesc(String pluginDesc) {
        this.pluginDesc = pluginDesc;
    }

    public String getPluginauthor() {
        return pluginauthor;
    }

    public void setPluginauthor(String pluginauthor) {
        this.pluginauthor = pluginauthor;
    }

    public String getPluginJsFile() {
        return pluginJsFile;
    }

    public void setPluginJsFile(String pluginJsFile) {
        this.pluginJsFile = pluginJsFile;
    }

    public String getPluginIcon() {
        return pluginIcon;
    }

    public void setPluginIcon(String pluginIcon) {
        this.pluginIcon = pluginIcon;
    }

    public String getPluginRes() {
        return pluginRes;
    }

    public void setPluginRes(String pluginRes) {
        this.pluginRes = pluginRes;
    }

}
