package com.cd.minecraft.mclauncher.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SKIN_ITEMS.
 */
public class SkinItems {

    private Long id;
    /** Not-null value. */
    private String skinName;
    private String skinDesc;
    private String skinauthor;
    private String skinFile;
    private String skinIcon;

    public SkinItems() {
    }

    public SkinItems(Long id) {
        this.id = id;
    }

    public SkinItems(Long id, String skinName, String skinDesc, String skinauthor, String skinFile, String skinIcon) {
        this.id = id;
        this.skinName = skinName;
        this.skinDesc = skinDesc;
        this.skinauthor = skinauthor;
        this.skinFile = skinFile;
        this.skinIcon = skinIcon;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getSkinName() {
        return skinName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSkinName(String skinName) {
        this.skinName = skinName;
    }

    public String getSkinDesc() {
        return skinDesc;
    }

    public void setSkinDesc(String skinDesc) {
        this.skinDesc = skinDesc;
    }

    public String getSkinauthor() {
        return skinauthor;
    }

    public void setSkinauthor(String skinauthor) {
        this.skinauthor = skinauthor;
    }

    public String getSkinFile() {
        return skinFile;
    }

    public void setSkinFile(String skinFile) {
        this.skinFile = skinFile;
    }

    public String getSkinIcon() {
        return skinIcon;
    }

    public void setSkinIcon(String skinIcon) {
        this.skinIcon = skinIcon;
    }

}
