package com.cd.minecraft.mclauncher.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TEXTURE_ITEMS.
 */
public class TextureItems {

    private Long id;
    /** Not-null value. */
    private String textureName;
    private String textureDesc;
    private String textureauthor;
    private String textureFile;
    private String textureIcon;

    public TextureItems() {
    }

    public TextureItems(Long id) {
        this.id = id;
    }

    public TextureItems(Long id, String textureName, String textureDesc, String textureauthor, String textureFile, String textureIcon) {
        this.id = id;
        this.textureName = textureName;
        this.textureDesc = textureDesc;
        this.textureauthor = textureauthor;
        this.textureFile = textureFile;
        this.textureIcon = textureIcon;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTextureName() {
        return textureName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTextureName(String textureName) {
        this.textureName = textureName;
    }

    public String getTextureDesc() {
        return textureDesc;
    }

    public void setTextureDesc(String textureDesc) {
        this.textureDesc = textureDesc;
    }

    public String getTextureauthor() {
        return textureauthor;
    }

    public void setTextureauthor(String textureauthor) {
        this.textureauthor = textureauthor;
    }

    public String getTextureFile() {
        return textureFile;
    }

    public void setTextureFile(String textureFile) {
        this.textureFile = textureFile;
    }

    public String getTextureIcon() {
        return textureIcon;
    }

    public void setTextureIcon(String textureIcon) {
        this.textureIcon = textureIcon;
    }

}
